import type { SlashCompletionSnapshot } from "./slash-completion.js";
import { sanitizeTerminalText, terminalWidth, truncateToTerminalWidth } from "./terminal-text.js";
import type { TerminalTheme } from "./theme.js";

const FULL_MENU_MIN_COLUMNS = 40;
const MAX_FRAME_WIDTH = 88;
const COMPACT_MAX_ROWS = 3;
const FOOTER = "↑↓ select · Tab/Enter complete · Esc close";
const COMPACT_FOOTER = "↑↓ · Tab · Esc";

const ANSI_SAVE_CURSOR = "\x1b[s";
const ANSI_RESTORE_CURSOR = "\x1b[u";
const ANSI_CURSOR_UP = "\x1b[A";
const ANSI_CLEAR_LINE = "\x1b[K";

/**
 * Pure menu formatting. The full mode draws a single-column box whose every
 * row (borders included) has the same visible width; below 40 columns a
 * compact borderless list is used. Descriptor text is sanitized before it can
 * reach the render path, so no control sequence can leak through.
 */
export function formatSlashMenu(
  snapshot: SlashCompletionSnapshot,
  options: { columns: number; theme: TerminalTheme },
): readonly string[] {
  if (!snapshot.active) {
    return [];
  }
  const { theme } = options;
  const safeColumns = Math.floor(options.columns);
  if (safeColumns < FULL_MENU_MIN_COLUMNS) {
    return formatCompact(snapshot, theme);
  }
  const width = Math.min(Math.max(safeColumns, FULL_MENU_MIN_COLUMNS) - 2, MAX_FRAME_WIDTH);
  return formatFull(snapshot, theme, width);
}

function formatFull(
  snapshot: SlashCompletionSnapshot,
  theme: TerminalTheme,
  width: number,
): string[] {
  const contentWidth = width - 4; // "│ " + body + " │"
  const matches = snapshot.matches;
  const padToWidth = (text: string, target: number): string => {
    const visible = terminalWidth(text);
    return visible >= target ? text : `${text}${" ".repeat(target - visible)}`;
  };

  const topPrefix = `╭─ Commands `;
  const top = theme.brandBorder(
    `${topPrefix}${"─".repeat(Math.max(0, width - terminalWidth(topPrefix) - 1))}╮`,
  );
  const bottomPrefix = `╰─ ${FOOTER} `;
  const bottom = theme.brandBorder(
    `${bottomPrefix}${"─".repeat(Math.max(0, width - terminalWidth(bottomPrefix) - 1))}╯`,
  );

  if (matches.length === 0) {
    const row = `│ ${padToWidth(theme.muted("No matching commands"), contentWidth)} │`;
    return [top, row, bottom];
  }

  const maxNameCells = Math.max(...matches.map((command) => terminalWidth(`/${command.name}`)));
  const nameColWidth = maxNameCells + 3; // "› "/"  " prefix plus one gap cell
  const descBudget = Math.max(1, contentWidth - nameColWidth);

  const rows = matches.map((command, index) => {
    const selected = index === snapshot.selectedIndex;
    const mark = selected ? theme.brandStrong("› ") : "  ";
    const name = selected
      ? theme.brandStrong(`/${command.name}`)
      : `/${command.name}`;
    const namePadding = " ".repeat(
      Math.max(0, nameColWidth - (terminalWidth(`/${command.name}`) + 2)),
    );
    const description = sanitizeTerminalText(command.description);
    const desc = description === ""
      ? ""
      : theme.muted(truncateToTerminalWidth(description, descBudget));
    const body = `${mark}${name}${namePadding}${desc}`;
    return `│ ${padToWidth(body, contentWidth)} │`;
  });

  return [top, ...rows, bottom];
}

function formatCompact(snapshot: SlashCompletionSnapshot, theme: TerminalTheme): string[] {
  const rows = snapshot.matches.slice(0, COMPACT_MAX_ROWS).map((command, index) =>
    index === snapshot.selectedIndex
      ? theme.brandStrong(`› /${command.name}`)
      : `  /${command.name}`,
  );
  if (rows.length === 0) {
    return [theme.muted("No matching commands"), theme.muted(COMPACT_FOOTER)];
  }
  return [...rows, theme.muted(COMPACT_FOOTER)];
}

export interface SlashMenuPresenterPort {
  render(snapshot: SlashCompletionSnapshot): void;
  clear(): void;
  suspend(): void;
  resume(snapshot: SlashCompletionSnapshot): void;
  close(): void;
}

export type SlashMenuPresenterOptions = {
  output: NodeJS.WritableStream & { columns?: number };
  theme: TerminalTheme;
  fallbackColumns?: number;
};

/**
 * Draws the menu into the temporary region below the readline input line.
 * Uses save/restore cursor so the input line is never disturbed; only
 * control sequences generated by the host are emitted — descriptor text never
 * enters a control sequence.
 */
export class SlashMenuPresenter implements SlashMenuPresenterPort {
  readonly #output: NodeJS.WritableStream & { columns?: number };
  readonly #theme: TerminalTheme;
  readonly #fallbackColumns: number;
  readonly #onResize = (): void => this.#redrawOnResize();
  #lastRows = 0;
  #lastSnapshot: SlashCompletionSnapshot | null = null;
  #suspended = false;
  #closed = false;

  constructor(options: SlashMenuPresenterOptions) {
    this.#output = options.output;
    this.#theme = options.theme;
    this.#fallbackColumns = options.fallbackColumns ?? 80;
    this.#output.on("resize", this.#onResize);
  }

  render(snapshot: SlashCompletionSnapshot): void {
    if (this.#closed || !snapshot.active) {
      return;
    }
    const lines = formatSlashMenu(snapshot, {
      columns: this.#columns(),
      theme: this.#theme,
    });
    this.#draw(lines);
    this.#lastSnapshot = snapshot;
    this.#suspended = false;
  }

  clear(): void {
    if (this.#closed) {
      return;
    }
    this.#clearRows();
  }

  suspend(): void {
    if (this.#closed) {
      return;
    }
    this.#clearRows();
    this.#suspended = true;
  }

  resume(snapshot: SlashCompletionSnapshot): void {
    if (this.#closed || !snapshot.active) {
      return;
    }
    const lines = formatSlashMenu(snapshot, {
      columns: this.#columns(),
      theme: this.#theme,
    });
    this.#draw(lines);
    this.#lastSnapshot = snapshot;
    this.#suspended = false;
  }

  close(): void {
    if (this.#closed) {
      return;
    }
    this.#clearRows();
    this.#output.off("resize", this.#onResize);
    this.#closed = true;
    this.#lastSnapshot = null;
  }

  #draw(lines: readonly string[]): void {
    // Clear any previously drawn menu region, then redraw from the input line.
    this.#clearRows();
    if (lines.length === 0) {
      return;
    }
    this.#output.write(ANSI_SAVE_CURSOR);
    for (const line of lines) {
      this.#output.write(`\r\n${line}${ANSI_CLEAR_LINE}`);
    }
    this.#output.write(ANSI_RESTORE_CURSOR);
    this.#lastRows = lines.length;
  }

  #clearRows(): void {
    for (let index = 0; index < this.#lastRows; index += 1) {
      this.#output.write(`${ANSI_CURSOR_UP}${ANSI_CLEAR_LINE}`);
    }
    this.#lastRows = 0;
  }

  #redrawOnResize(): void {
    if (this.#closed || this.#lastSnapshot === null || this.#suspended) {
      return;
    }
    this.render(this.#lastSnapshot);
  }

  #columns(): number {
    const columns = this.#output.columns;
    if (typeof columns !== "number" || !Number.isFinite(columns) || columns <= 0) {
      return this.#fallbackColumns;
    }
    return Math.floor(columns);
  }
}
